# Generated by Django 5.0.6 on 2024-06-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateHinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('HU', 'Hino da Umbanda'), ('HA', 'Hinos da Ayahuasca'), ('HMI', 'Hinario do Mestre Irineu'), ('A', 'Abertura'), ('SP', 'Saldação da Porteira'), ('DF', 'Defumação'), ('DS', 'Descarrego'), ('EN', 'Encerramento'), ('Estrela', 'Oxalá'), ('Espada', 'Ogum'), ('Almas', 'Omulu/Obaluaê'), ('Mar', 'Iemanjá'), ('Machado', 'Xangô'), ('Bodoque', 'Oxossi'), ('Coração', 'Oxum'), ('Raio', 'Iansã'), ('Vassora', 'Nanã Buruquê'), ('Pirulito', 'Crianças'), ('Barquinho', 'Marinheiros/Marujos'), ('Laço', 'Boiaderos'), ('Chapéu', 'Baianos'), ('PV', 'Pretos Velhos'), ('Arco', 'Cabolos'), ('Tridente', 'Exus')], max_length=300)),
                ('letra', models.TextField()),
                ('dateofpost', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
