# Generated by Django 5.0.6 on 2024-06-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createhinario',
            name='categoria',
            field=models.CharField(choices=[('Hino da Umbanda', 'Hino da Umbanda'), ('Hinos da Ayahuasca', 'Hinos da Ayahuasca'), ('Hinario do Mestre Irineu', 'Hinario do Mestre Irineu'), ('Abertura', 'Abertura'), ('Saldação da Porteira', 'Saldação da Porteira'), ('Defumação', 'Defumação'), ('Descarrego', 'Descarrego'), ('Encerramento', 'Encerramento'), ('Oxalá', 'Oxalá'), ('Ogum', 'Ogum'), ('Omulu/Obaluaê', 'Omulu/Obaluaê'), ('Iemanjá', 'Iemanjá'), ('Xangô', 'Xangô'), ('Oxossi', 'Oxossi'), ('Oxum', 'Oxum'), ('Iansã', 'Iansã'), ('Nanã Buruquê', 'Nanã Buruquê'), ('Crianças', 'Crianças'), ('Marinheiros/Marujos', 'Marinheiros/Marujos'), ('Boiaderos', 'Boiaderos'), ('Baianos', 'Baianos'), ('Pretos Velhos', 'Pretos Velhos'), ('Caboclos', 'Caboclos'), ('Exus/Pomba Giras', 'Exus/Pomba Giras')], max_length=300),
        ),
    ]
