# Generated by Django 5.0.6 on 2024-06-20 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0002_alter_createhinario_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createhinario',
            name='dateofpost',
        ),
        migrations.RemoveField(
            model_name='createhinario',
            name='letra',
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.TextField()),
                ('dateofpost', models.DateTimeField(auto_now_add=True)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pontos.createhinario')),
            ],
        ),
    ]
