# Generated by Django 5.0.6 on 2024-06-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0003_remove_createhinario_dateofpost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='letra',
        ),
        migrations.AddField(
            model_name='ponto',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pontos.createhinario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ponto',
            name='ponto',
            field=models.TextField(),
        ),
    ]
