# Generated by Django 5.0.6 on 2024-06-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0004_remove_ponto_letra_ponto_category_alter_ponto_ponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='createhinario',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
