# Generated by Django 5.0.6 on 2024-06-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0005_createhinario_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='createhinario',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
